# Generated by Django 4.1 on 2023-09-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='value',
            field=models.CharField(default='', max_length=128),
        ),
    ]
