# Generated by Django 4.1 on 2023-09-05 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MediaManagement', '0002_field_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MediaManagement.category'),
        ),
        migrations.AlterField(
            model_name='media',
            name='coordinadas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MediaManagement.coordinadas'),
        ),
        migrations.AlterField(
            model_name='media',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MediaManagement.plan'),
        ),
    ]
