# Generated by Django 4.1 on 2023-09-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaManagement', '0003_alter_media_category_alter_media_coordinadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
