# Generated by Django 4.1 on 2023-09-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaManagement', '0004_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
