# Generated by Django 4.1 on 2023-09-08 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MediaManagement', '0005_alter_plan_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='media',
        ),
        migrations.CreateModel(
            name='Media_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MediaManagement.field')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MediaManagement.media')),
            ],
            options={
                'verbose_name': 'media_field',
            },
        ),
    ]
