# Generated by Django 4.1 on 2023-09-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediaManagement', '0006_remove_field_media_media_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='media_field',
            unique_together={('media', 'field')},
        ),
    ]
