# Generated by Django 4.1 on 2023-09-16 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MediaManagement', '0007_alter_media_field_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_field',
            name='link',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='media_field',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_fields', to='MediaManagement.media'),
        ),
    ]
