# Generated by Django 4.1 on 2023-10-02 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MediaManagement', '0009_remove_media_field_link_field_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mediacontainer',
            name='father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='son_containers', to='MediaManagement.media'),
        ),
        migrations.AlterField(
            model_name='mediacontainer',
            name='son',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='father_containers', to='MediaManagement.media'),
        ),
    ]
