# Generated by Django 4.1 on 2023-08-31 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
